### ISSUE TITLE
object locations?

### ISSUE THREAD

**Issue by vpenades** [simonowen/sentland#1]
H!, I finally got time to test the land generator, I was able to move the code to c# and write a small viewer, looking like this:
![imagen](https://user-images.githubusercontent.com/5433822/160647511-21b5c4ca-36f7-48fb-a87e-6e9a43361f97.png)

Any chance of extracting the formula for the sentinel, sentries, the player's start position, the trees and the blocks?

My guess is that the sentinel's start position is the hightest location closest to the center of the map, but no clue about anything else.

**Comment by simonowen** [comment]
Object placement was added in e98fe387caa950faa1ed89c7dd13f24084e42a91.

Also be sure to check the landscape generation fixes in 01f45e0c4aec3a95f2648c11b2bbd0d4d6556583, which caused minor differences in a few cases.

**Comment by vpenades** [comment]
I'll check the code changes and compare them to my port.

Btw, it could be great to have a dump of the heightmaps of some random levels to use them on unit testing.

**Comment by simonowen** [comment]
The `golden` sub-directory has a few samples, which are used for runtime checks if those landscape numbers are generated.  The "despike3" data files hold the final heights if you want a few to check against. Note that these files are in _memory_ order as used by the original code, not the linear rows and colums used by the script. The default save format is linear but you can use `-m` to output in the same format as despike3.

The `iterations.bin` check in the latest script gives another level of consistency checking that is effective at detecting errors in the landscape and object logic. Adding that alerted me to the subtle issues in some landscapes, which I hadn't spotted until then. I've checked the current script generates all 57344 with the same iteration count as the emulation, which gives me good confidence.

I could create another file similar to `iterations.bin` with hashes of each landscape's data, for checking against the final data. The object data could probably be scraped and hashed too -- it's scattered across different tables in the original game. The golden files were useful for identifying issues in different generation passes but checking the final generated data is all that unit tests need to cover.
